"""add_provider_registration_fields

Revision ID: ec498189aa61
Revises: c0df21784762
Create Date: 2026-10-04 14:55:10.753924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec498189aa61'
down_revision: Union[str, None] = 'c0df21784762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('whatsapp_number', sa.String(length=20), nullable=True))
    op.add_column('providers', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('providers', sa.Column('cnic', sa.String(length=15), nullable=True))
    op.add_column('providers', sa.Column('business_reg_number', sa.String(length=50), nullable=True))
    op.alter_column('providers', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('providers', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('providers', 'business_reg_number')
    op.drop_column('providers', 'cnic')
    op.drop_column('providers', 'description')
    op.drop_column('providers', 'whatsapp_number')
    # ### end Alembic commands ###
